promise.catch(function (error) {
    console.log("catch: " + error);
}); 